# The best

name: Sync Files To Main Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  upload:
    name: Sync Files
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set Git Config
        run: |
          echo "${{ secrets.ftp_main_password }}" > key.pem
          git config git-ftp.url ${{ secrets.ftp_main_server }}
          git config git-ftp.user ${{ secrets.ftp_main_username }}
          git config git-ftp.key key.pem
          git config git-ftp.insecure "1"
          echo "::add-mask::${{ secrets.ftp_main_hostname }}"
      
      - name: Sync BossHud Files
        run: git ftp push --verbose --auto-init --syncroot "bosshud" --remote-root "csgo/addons/sourcemod/configs/MapBossHP/"

      - name: Sync BSP CVar Whitelist Files
        run: git ftp push --verbose --auto-init --syncroot "bspconvar_whitelist" --remote-root "csgo/"

      - name: Sync entWatch Files
        run: git ftp push --verbose --auto-init --syncroot "entwatch" --remote-root "csgo/cfg/sourcemod/entwatch/maps/"

      - name: Sync SaveLevel Files
        run: git ftp push --verbose --auto-init --syncroot "savelevel" --remote-root "csgo/addons/sourcemod/configs/savelevel/"

      - name: Sync Stripper Files
        run: git ftp push --verbose --auto-init --syncroot "stripper" --remote-root "csgo/addons/stripper/maps/"

      - name: Sync VScript Files
        run: git ftp push --verbose --auto-init --syncroot "vscripts" --remote-root "csgo/scripts/vscripts/gfl/"

      - name: Sync ZombieReloaded Files
        run: git ftp push --verbose --auto-init --syncroot "zombiereloaded" --remote-root "csgo/cfg/sourcemod/zombiereloaded/"

      - name: Sync MusicName Files
        run: git ftp push --verbose --auto-init --syncroot "musicname" --remote-root "csgo/addons/sourcemod/configs/MusicName/"